### ISSUE TITLE
Size of Open Source

### ISSUE THREAD

**Issue by chadwhitacre** [chadwhitacre/openpath#16]
Read "[The Value of Open Source Software](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4693148)." ([h/t](https://twitter.com/jonathimer/status/1748775612775620710), [also](https://twitter.com/coni2k/status/1750147944601264627))

Revisit "[Open Source Captures 0.02% of the Value it Creates, Leaving $852B/yr on the Table](https://gratipay.news/open-source-captures-almost-none-of-the-value-it-creates-9015eb7e293e)."

[SSRN-id4693148.pdf](https://github.com/chadwhitacre/openpath/files/14012748/SSRN-id4693148.pdf)

**Comment by chadwhitacre** [comment]
I read it, starting a post, two big questions:

1. "Buy, borrow, build" — If borrow is off the table, why assume that all companies have to individually rebuild all OSS from scratch vs. buying from others? Seems a big impact on demand number.
1. Also on the demand side, why is Go such a big bar?

**Comment by chadwhitacre** [comment]
[**Questioning “The Value of Open Source Software”**](https://openpath.chadwhitacre.com/2024/questioning-the-value-of-open-source-software/)
_The new HBS working paper seems fundamentally flawed to me, though it has some helpful parts._

**Comment by coni2k** [comment]
> [**Questioning “The Value of Open Source Software”**](https://openpath.chadwhitacre.com/2024/questioning-the-value-of-open-source-software/) _The new HBS working paper seems fundamentally flawed to me, though it has some helpful parts._

My two cents: I don't think the demand value calculation is meant to be taken literally. I took it as the upper limit of the cost parameter. As you mentioned, that situation can never happen in practice due to the usual market dynamics. However, having such a figure could give us better estimations in the future, or if we could periodically calculate these figures, we could get a better understanding based on the changes in time.

My suggestion is to base the value of open technologies on closed/proprietary technologies, at least as a starting point. Add a 1% consumption tax on closed tech to generate at least an entry-level, steady revenue for open tech. What the upper limit should be (2 percent, 5, 10, or more) requires a lengthier discussion. But, in short, I'm also much more close to Nordhaus & Goods-Market Valuation approach:
> This method builds on suggestions from Nordhaus (2006, p. 146) who says "…the price of market and nonmarket goods and services should be imputed on the basis of the comparable market goods and services."

It would be great to see the study's model/data so we could also review the results. Indeed, the Go language results seem like a strange outlier.

**Comment by chadwhitacre** [comment]
> demand value calculation is meant to be taken literally

Over on LinkedIn I see Frank [saying](https://www.linkedin.com/feed/update/urn:li:activity:7153827260687347712?commentUrn=urn%3Ali%3Acomment%3A%28activity%3A7153827260687347712%2C7153849664897695744%29&replyUrn=urn%3Ali%3Acomment%3A%28activity%3A7153827260687347712%2C7153852309351841792%29&dashCommentUrn=urn%3Ali%3Afsd_comment%3A%287153849664897695744%2Curn%3Ali%3Aactivity%3A7153827260687347712%29&dashReplyUrn=urn%3Ali%3Afsd_comment%3A%287153852309351841792%2Curn%3Ali%3Aactivity%3A7153827260687347712%29), "the true number is likely much higher!" 🙄

> It would be great to see the study's model/data so we could also review the results.

:100:
